import type { GrammarSection } from "./types";

export const verbos: GrammarSection = {
  id: "verbos",
  badge: "06",
  title: "Verbos Esenciales",
  tag: "Vocabulario",
  description: "Domina los verbos regulares e irregulares más comunes en inglés. ¡La práctica hace al maestro!",
  rule: {
    name: "Regulares vs. Irregulares",
    explanation: "Los verbos regulares forman su pasado y participio añadiendo '-ed'. Los irregulares no siguen un patrón fijo y deben memorizarse. Usa el interruptor para explorar ambas listas.",
    formulas: ["Regulares: work → worked", "Irregulares: go → went → gone"],
  },
  content: [
    {
      type: "paragraph",
      text: "Los verbos son el corazón de cualquier idioma. En inglés, entender la diferencia entre verbos regulares e irregulares es un paso fundamental. Los verbos regulares son predecibles, pero los irregulares, a pesar de ser menos, son los que más se usan en el día a día. ¡A memorizarlos!",
    },
    {
      type: "verb-table",
      title: "Lista de Verbos Comunes",
      irregularVerbs: [
        // Top Tier
        { infinitive: "be", simplePast: "was/were", pastParticiple: "been", spanish: "ser/estar" },
        { infinitive: "have", simplePast: "had", pastParticiple: "had", spanish: "tener" },
        { infinitive: "do", simplePast: "did", pastParticiple: "done", spanish: "hacer" },
        { infinitive: "say", simplePast: "said", pastParticiple: "said", spanish: "decir" },
        { infinitive: "go", simplePast: "went", pastParticiple: "gone", spanish: "ir" },
        { infinitive: "get", simplePast: "got", pastParticiple: "got/gotten", spanish: "obtener" },
        { infinitive: "make", simplePast: "made", pastParticiple: "made", spanish: "hacer/fabricar" },
        { infinitive: "know", simplePast: "knew", pastParticiple: "known", spanish: "saber/conocer" },
        { infinitive: "think", simplePast: "thought", pastParticiple: "thought", spanish: "pensar" },
        { infinitive: "see", simplePast: "saw", pastParticiple: "seen", spanish: "ver" },
        { infinitive: "come", simplePast: "came", pastParticiple: "come", spanish: "venir" },
        { infinitive: "take", simplePast: "took", pastParticiple: "taken", spanish: "tomar/llevar" },
        // Mid Tier
        { infinitive: "give", simplePast: "gave", pastParticiple: "given", spanish: "dar" },
        { infinitive: "find", simplePast: "found", pastParticiple: "found", spanish: "encontrar" },
        { infinitive: "tell", simplePast: "told", pastParticiple: "told", spanish: "decir/contar" },
        { infinitive: "become", simplePast: "became", pastParticiple: "become", spanish: "convertirse en" },
        { infinitive: "show", simplePast: "showed", pastParticiple: "shown/showed", spanish: "mostrar" },
        { infinitive: "leave", simplePast: "left", pastParticiple: "left", spanish: "dejar/irse" },
        { infinitive: "feel", simplePast: "felt", pastParticiple: "felt", spanish: "sentir" },
        { infinitive: "put", simplePast: "put", pastParticiple: "put", spanish: "poner" },
        { infinitive: "bring", simplePast: "brought", pastParticiple: "brought", spanish: "traer" },
        { infinitive: "begin", simplePast: "began", pastParticiple: "begun", spanish: "empezar" },
        { infinitive: "keep", simplePast: "kept", pastParticiple: "kept", spanish: "mantener/guardar" },
        { infinitive: "write", simplePast: "wrote", pastParticiple: "written", spanish: "escribir" },
        { infinitive: "stand", simplePast: "stood", pastParticiple: "stood", spanish: "estar de pie" },
        { infinitive: "hear", simplePast: "heard", pastParticiple: "heard", spanish: "oír" },
        { infinitive: "run", simplePast: "ran", pastParticiple: "run", spanish: "correr" },
        { infinitive: "read", simplePast: "read", pastParticiple: "read", spanish: "leer" },
        { infinitive: "speak", simplePast: "spoke", pastParticiple: "spoken", spanish: "hablar" },
        { infinitive: "eat", simplePast: "ate", pastParticiple: "eaten", spanish: "comer" },
        { infinitive: "drink", simplePast: "drank", pastParticiple: "drunk", spanish: "beber" },
        { infinitive: "sleep", simplePast: "slept", pastParticiple: "slept", spanish: "dormir" },
      ],
      regularVerbs: [
        { infinitive: "look", simplePast: "looked", pastParticiple: "looked", spanish: "mirar" },
        { infinitive: "use", simplePast: "used", pastParticiple: "used", spanish: "usar" },
        { infinitive: "work", simplePast: "worked", pastParticiple: "worked", spanish: "trabajar" },
        { infinitive: "call", simplePast: "called", pastParticiple: "called", spanish: "llamar" },
        { infinitive: "try", simplePast: "tried", pastParticiple: "tried", spanish: "intentar" },
        { infinitive: "ask", simplePast: "asked", pastParticiple: "asked", spanish: "preguntar" },
        { infinitive: "need", simplePast: "needed", pastParticiple: "needed", spanish: "necesitar" },
        { infinitive: "seem", simplePast: "seemed", pastParticiple: "seemed", spanish: "parecer" },
        { infinitive: "help", simplePast: "helped", pastParticiple: "helped", spanish: "ayudar" },
        { infinitive: "play", simplePast: "played", pastParticiple: "played", spanish: "jugar" },
        { infinitive: "move", simplePast: "moved", pastParticiple: "moved", spanish: "mover" },
        { infinitive: "live", simplePast: "lived", pastParticiple: "lived", spanish: "vivir" },
        { infinitive: "believe", simplePast: "believed", pastParticiple: "believed", spanish: "creer" },
        { infinitive: "happen", simplePast: "happened", pastParticiple: "happened", spanish: "suceder" },
        { infinitive: "watch", simplePast: "watched", pastParticiple: "watched", spanish: "ver/observar" },
        { infinitive: "follow", simplePast: "followed", pastParticiple: "followed", spanish: "seguir" },
        { infinitive: "stop", simplePast: "stopped", pastParticiple: "stopped", spanish: "parar" },
        { infinitive: "create", simplePast: "created", pastParticiple: "created", spanish: "crear" },
        { infinitive: "walk", simplePast: "walked", pastParticiple: "walked", spanish: "caminar" },
        { infinitive: "want", simplePast: "wanted", pastParticiple: "wanted", spanish: "querer" },
        { infinitive: "like", simplePast: "liked", pastParticiple: "liked", spanish: "gustar" },
        { infinitive: "love", simplePast: "loved", pastParticiple: "loved", spanish: "amar" },
        { infinitive: "start", simplePast: "started", pastParticiple: "started", spanish: "empezar" },
        { infinitive: "study", simplePast: "studied", pastParticiple: "studied", spanish: "estudiar" },
        { infinitive: "change", simplePast: "changed", pastParticiple: "changed", spanish: "cambiar" },
      ],
    },
  ],
  quiz: [
    {
      question: "¿Cuál es el Pasado Simple del verbo 'to go'?",
      options: ["goed", "gone", "went"],
      correctAnswerIndex: 2,
      explanation: "'go' es un verbo irregular. Su Pasado Simple es 'went' y su Participio Pasado es 'gone'.",
    },
    {
      question: "¿Cuál de estos verbos es REGULAR?",
      options: ["eat", "work", "see"],
      correctAnswerIndex: 1,
      explanation: "'work' es un verbo regular. Su pasado es 'worked'. 'Eat' (ate/eaten) y 'see' (saw/seen) son irregulares.",
    },
    {
      question: "Completa la oración: 'Yesterday, I ______ a movie.'",
      options: ["watched", "watch", "was watching"],
      correctAnswerIndex: 0,
      explanation: "Para una acción completada en el pasado como 'yesterday', usamos el Pasado Simple. 'Watch' es un verbo regular, por lo que añadimos '-ed'.",
    },
     {
      question: "¿Cuál es el Participio Pasado de 'to write'?",
      options: ["wrote", "written", "writed"],
      correctAnswerIndex: 1,
      explanation: "El verbo 'write' es irregular. Su participio pasado es 'written', usado en tiempos como el Presente Perfecto (I have written).",
    },
    {
      question: "¿Cuál es el Pasado Simple de 'to drink'?",
      options: ["drunken", "drank", "drinked"],
      correctAnswerIndex: 1,
      explanation: "'Drink' es un verbo irregular. Su Pasado Simple es 'drank'.",
    },
    {
      question: "Completa: 'He has ______ me a beautiful gift.'",
      options: ["gave", "given", "gived"],
      correctAnswerIndex: 1,
      explanation: "Con 'has' (Presente Perfecto), se necesita el Participio Pasado. El participio de 'give' es 'given'.",
    },
    {
      question: "¿Cuál de estos verbos es IRREGULAR?",
      options: ["start", "feel", "ask"],
      correctAnswerIndex: 1,
      explanation: "'Feel' es irregular (felt/felt). 'Start' (started) y 'ask' (asked) son regulares.",
    }
  ],
};
